eng_comp_7 = [
    'Introdução À Lógica Para A Computação',
    'Fundamentos De Programação 1',
    'Física Teórica A',
    'Cálculo Diferencial E Integral 1',
    'Geometria Analítica E Álgebra Linear',
    'Técnicas De Programação',
    'Estrutura De Dados 1',
    'Introdução À Práticas De Laboratório Em Eletricidade E Eletrônica',
    'Física Experimental 1',
    'Física Teórica B',
    'Cálculo Diferencial E Integral 2',
    'Química',
    'Estrutura De Dados 2',
    'Eletricidade',
    'Oficina De Integração 1',
    'Física Teórica C',
    'Equações Diferenciais Ordinárias',
    'Probabilidade E Estatística',
    'Cálculo Diferencial E Integral 3',
    'Matemática Discreta',
    'Circuitos Elétricos',
    'Circuitos Digitais',
    'Desenho Técnico',
    'Análise De Sistemas Lineares',
    'Física Experimental 2',
    'Física Teórica D',
    'Projeto E Análise De Algoritmos',
    'Introdução A Banco De Dados',
    'Análise E Projeto De Sistemas',
    'Comunicação De Dados',
    'Arquitetura E Organização De Computadores',
    'Eletrônica Geral 1',
    'Desenho Técnico Aplicado',
    ]

eng_comp = [
    'Introdução À Lógica Para A Computação',
    'Fundamentos De Programação 1',
    'Física Teórica A',
    'Cálculo Diferencial E Integral 1',
    'Geometria Analítica E Álgebra Linear',
    'Técnicas De Programação',
    'Estrutura De Dados 1',
    'Introdução À Práticas De Laboratório Em Eletricidade E Eletrônica',
    'Física Experimental 1',
    'Física Teórica B',
    'Cálculo Diferencial E Integral 2',
    'Química',
    'Estrutura De Dados 2',
    'Eletricidade',
    'Oficina De Integração 1',
    'Física Teórica C',
    'Equações Diferenciais Ordinárias',
    'Probabilidade E Estatística',
    'Cálculo Diferencial E Integral 3',
    'Matemática Discreta',
    'Circuitos Elétricos',
    'Circuitos Digitais',
    'Desenho Técnico',
    'Análise De Sistemas Lineares',
    'Física Experimental 2',
    'Física Teórica D',
    'Projeto E Análise De Algoritmos',
    'Introdução A Banco De Dados',
    'Análise E Projeto De Sistemas',
    'Comunicação De Dados',
    'Arquitetura E Organização De Computadores',
    'Eletrônica Geral 1',
    'Desenho Técnico Aplicado',
    'Sociologia',
    'Teoria Da Computação',
    'Engenharia De Software',
    'Sistemas Operacionais',
    'Sistemas Microcontrolados',
    'Estágio Supervisionado',
    'Eletrônica Geral 2',
    'Oficina De Integração 2',
    'Sistemas Inteligentes',
    'Redes De Computadores',
    'Sistemas Embarcados',
    'Lógica Reconfigurável',
    'Controle 1',
    'Processamento Digital De Sinais',
    'Filosofia Da Ciência E Da Tecnologia',
    'Algoritmos E Complexidade',
    'Complexidade Computacional',
    'Teoria Dos Grafos',
    'Computação Quântica',
    'Introdução À Criptografia',
    'Geometria Computacional',
    'Bibliotecas Digitais',
    'Banco De Dados 2',
    'Computação Baseada Em Dados',
    'Tópicos Em Banco De Dados',
    'Banco De Dados',
    'Recuperação Inteligente De Informações',
    'Data Warehousing',
    'Introduction To Data Science',
    'Simulação De Eventos Discretos',
    'Programação Matemática',
    'Simulação De Sistemas Biológicos E Sociais',
    'Modelagem E Avaliação De Sistemas',
    'Otimização De Sistemas',
    'Introdução À Computação Científica',
    'Métodos Estocásticos',
    'Métodos Formais Ii',
    'Tópicos Especiais Em Telemática Iii',
    'Engenharia De Software 2',
    'Engenharia De Requisitos',
    'Metodologias Ágeis Para O Desenvolvimento De Software',
    'Testes, Verificação E Validação De Sistemas',
    'Sistemas Legados',
    'Modelagem De Software',
    'Métricas E Estimativas De Software',
    'Gerência De Projetos',
    'Qualidade De Software',
    'Tecnologias Da Informação Aplicada À Gestão',
    'Gestão Do Conhecimento',
    'Sistemas De Apoio À Decisão',
    'Informática Em Saúde',
    'Sistemas De Informação Em Saúde',
    'Inteligência Coletiva E Redes Sociais Eletrônicas',
    'Modelagem De Processos De Negócios',
    'Sistemas De Informação E Organizações',
    'Introdução À Interação Humano-Computador',
    'Avaliação Em Interação Humano-Computador',
    'Acessibilidade E Inclusão Digital',
    'Trabalho Cooperativo Apoiado Por Computador',
    'Computação E Sociedade',
    'Tópicos Em Design De Interação',
    'Fundamentos Em Interação',
    'Design De Interação',
    'Redes Neurais',
    'Meta-Heuristicas Inspiradas Em Inteligência Coletiva',
    'Computação Evolucionária',
    'Inteligência Artificial Distribuída',
    'Mineração De Dados',
    'Ontologias',
    'Sistemas Autônomos Inteligentes',
    'Sistemas Fuzzy',
    'Introdução Às Ciências Cognitivas',
    'Data Mining',
    'Estrutura De Linguagens De Programação',
    'Construção De Compiladores',
    'Desenvolvimento Integrado De Sistemas',
    'Html/Css',
    'Desenvolvimento De Aplicações Web',
    'Infraestrutura Para Tecnologia De Informação',
    'Programação Para Dispositivos Móveis E Sem Fio',
    'Web Design',
    'Cabeamento Estruturado',
    'Redes E Sistemas De Comunicação Móveis',
    'Oficina De Redes',
    'Infraestrutura De Lans Hierarquicas',
    'Infraestrutura De Wans',
    'Segurança De Redes E Sistemas',
    'Projeto De Infraestrutura De Redes',
    'Redes Sem Fio',
    'Simulação E Análise De Desempenho De Redes De Computadores',
    'Comunicações Sem Fio',
    'Sistemas Distribuídos',
    'Desenvolvimento De Objetos De Aprendizagem',
    'Design Instrucional',
    'Informática Na Educação',
    'Introdução À Educação À Distância',
    'Sistemas Hipermidia Adaptativos',
    'Processamento Digital De Imagens',
    'Computação Gráfica',
    'Introdução À Visão Computacional',
    'Tópicos Avançados Em Processamento Gráfico',
    'Processamento Digital De Imagens 2',
    'Reconhecimento De Padrões Em Imagens',
    'Computação Gráfica 2',
    'Visão Computacional',
    'Fundamentos Do Processamento De Imagens Médicas',
    'Arquitetura Avançada De Computadores',
    'Arquitetura De Computadores Paralelos',
    'Robótica Móvel',
    'Engenharia De Sistemas Aplicada A Sistemas Ciberfísicos',
    'Sistemas De Tempo Real',
    'Laboratório De Processamento Digital De Sinais',
    'Lógica Programável E Vhdl',
    'Tópicos Avançados Em Sistemas Embarcados',
    'Programação Orientada A Notificações',
    'Web Design',
    'Libras A',
    'Libras B',
    'Laboratório De Controle Discreto',
    'Controle Supervisório',
    'Controle Inteligente',
    'Identificação De Sistemas',
    'Controle 3',
    'Controle 4',
    'Controle À Eventos Discretos',
    'Fotônica',
    'Introdução À Microeletrônica',
    'Oficina De Integração 3',
    'Engenharia Biomédica',
    'Bioengenharia',
    'Engenharia Médica',
    'Engenharia Clínica',
    'Instrumentação E Transdução Biomédica I',
    'Instrumentação E Transdução Biomédica Ii',
    'Introdução À Robótica',
    'Comunicações Ópticas',
    'Processamento Da Informação',
    'Tópicos Em Comunicações',
    'Sistemas De Comunicação 1',
    'Sistemas De Comunicação 2',
    'Gestão Da Qualidade',
    'Gestão De Projetos Tecnológicos',
    'Gestão Estratégica De Tecnologia E Inovação',
    'Confiabilidade',
    'Fabricação Eletrônica',
    'Eletromagnetismo',
    'Propagação De Ondas E Guias',
    'Sensores E Atuadores',
    'Linhas De Transmissão E Antenas',
    'Psicologia Aplicada Ao Trabalho',
    'A Presença Africana No Brasil: Tecnologia E Trabalho',
    'História Da Técnica E Da Tecnologia',
    'Mecânica Geral 1',
    'Mecânica Geral 2',
    'Fenômenos De Transporte 1',
    'Fenômenos De Transporte 2',
    'Ótica',
    'Economia',
    'Gestão De Pessoas',
    'Compiladores',
    'Bigdata - Processamento E Análise De Dados Em Grande Escala',
    'Servidores E Aplicações Para Linux',
    'Nosql - Bancos De Dados Não Relacionais',
    'Tópicos Matemáticos Para Engenheiros',
    'Cálculo Numérico',
    'Educação Ambiental',
    'Energia E Meio Ambiente',
    'Desenvolvimento Sustentável',
    'Ecologia',
    'Trabalho De Conclusão De Curso 1',
    'Gestão Financeira',
    'Ciências Do Ambiente',
    'Trabalho De Conclusão De Curso 2',
    'Ética, Profissão E Cidadania',
]


# agora começa BSI


sist_info = [
    'Fundamentos De Programação 1',
    'Prolegômenos Ao Computar',
    'Tópicos Matemáticos',
    'Introdução À Lógica Para A Computação',
    'Técnicas De Programação',
    'Estrutura De Dados 1',
    'Fundamentos De Sistemas De Informação',
    'Geometria Analítica E Álgebra Linear',
    'Teoria Da Computação',
    'Matemática Discreta',
    'Engenharia De Software 2',
    'Estrutura De Dados 2',
    'Gestão Da Informação Em Sistemas De Informação',
    'Introdução À Interação Humano-Computador',
    'Sistemas Inteligentes',
    'Desenvolvimento Integrado De Sistemas',
    'Processamento Digital De Imagens',
    'Arquitetura E Organização De Computadores',
    'Eletricidade',
    'Sociologia',
    'História Da Técnica E Da Tecnologia',
    'Teorias Da Administração',
    'Comportamento Humano Nas Organizações',
    'Probabilidade E Estatística',
    'Projeto E Análise De Algoritmos',
    'Algoritmos E Complexidade',
    'Complexidade Computacional',
    'Teoria Dos Grafos',
    'Computação Quântica',
    'Introdução À Criptografia',
    'Geometria Computacional',
    'Introdução A Banco De Dados',
    'Bibliotecas Digitais',
    'Banco De Dados 2',
    'Computação Baseada Em Dados',
    'Banco De Dados',
    'Recuperação Inteligente De Informações',
    'Data Warehousing',
    'Introdução A Ciências De Dados',
    'Introduction To Data Science',
    'Simulação De Eventos Discretos',
    'Programação Matemática',
    'Simulação De Sistemas Biológicos E Sociais',
    'Modelagem E Avaliação De Sistemas',
    'Otimização De Sistemas',
    'Introdução À Computação Científica',
    'Teoria De Filas',
    'Métodos Estocásticos',
    'Metaheurística',
    'Engenharia De Requisitos',
    'Metodologias Ágeis Para O Desenvolvimento De Software',
    'Testes, Verificação E Validação De Sistemas',
    'Sistemas Legados',
    'Modelagem De Software',
    'Métricas E Estimativas De Software',
    'Gerência De Projetos',
    'Qualidade De Software',
    'Análise E Projeto De Sistemas',
    'Tecnologias Da Informação Aplicada À Gestão',
    'Gestão Do Conhecimento',
    'Sistemas De Apoio À Decisão',
    'Informática Em Saúde',
    'Sistemas De Informação Em Saúde',
    'Inteligência Coletiva E Redes Sociais Eletrônicas',
    'Modelagem De Processos De Negócios',
    'Sistemas De Informação E Organizações',
    'Avaliação Em Interação Humano-Computador',
    'Acessibilidade E Inclusão Digital',
    'Trabalho Cooperativo Apoiado Por Computador',
    'Computação E Sociedade',
    'Tópicos Em Design De Interação',
    'Fundamentos Em Interação',
    'Design De Interação',
    'Redes Neurais',
    'Meta-Heuristicas Inspiradas Em Inteligência Coletiva',
    'Inteligência Artificial',
    'Computação Evolucionária',
    'Inteligência Artificial Distribuída',
    'Mineração De Dados',
    'Ontologias',
    'Sistemas Autônomos Inteligentes',
    'Sistemas Fuzzy',
    'Introdução Às Ciências Cognitivas',
    'Data Mining',
    'Estrutura De Linguagens De Programação',
    'Construção De Compiladores',
    'Html/Css',
    'Desenvolvimento De Aplicações Web',
    'Infraestrutura Para Tecnologia De Informação',
    'Programação Para Dispositivos Móveis E Sem Fio',
    'Web Design',
    'Sistemas Operacionais',
    'Cabeamento Estruturado',
    'Comunicação De Dados',
    'Redes E Sistemas De Comunicação Móveis',
    'Oficina De Redes',
    'Infraestrutura De Lans Hierarquicas',
    'Infraestrutura De Wans',
    'Segurança De Redes E Sistemas',
    'Projeto De Infraestrutura De Redes',
    'Roteamento E Qualidade De Serviços Em Redes',
    'Redes Sem Fio',
    'Simulação E Análise De Desempenho De Redes De Computadores',
    'Computação Gráfica',
    'Introdução À Visão Computacional',
    'Tópicos Avançados Em Processamento Gráfico',
    'Processamento Digital De Imagens 2',
    'Reconhecimento De Padrões Em Imagens',
    'Computação Gráfica 2',
    'Visão Computacional',
    'Fundamentos Do Processamento De Imagens Médicas',
    'Fundamentos De Circuitos Digitais',
    'Sistemas Microcontrolados',
    'Sistemas Embarcados',
    'Lógica Reconfigurável',
    'Arquitetura Avançada De Computadores',
    'Arquitetura De Computadores Paralelos',
    'Robótica Móvel',
    'Engenharia De Sistemas Aplicada A Sistemas Ciberfísicos',
    'Sistemas Embarcados Ppgca',
    'Computação Reconfigurável',
    'Tópicos Avançados Em Sistemas Embarcados',
    'Trabalho De Integração 1',
    'Legislação Para Informática',
    'Teorias Organizacionais',
    'Cálculo Numérico',
    'Comunicação Oral E Escrita',
    'Engenharia De Software',
    'Redes De Computadores',
    'Estágio 1',
    'Libras 1',
    'Libras 2',
    'Psicologia Aplicada Ao Trabalho',
    'Fundamentos Da Ética',
    'A Presença Africana No Brasil: Tecnologia E Trabalho',
    'Filosofia Da Ciência E Da Tecnologia',
    'Responsabilidade Social E Desenvolvimento Sustentável',
    'Ciências Do Ambiente',
    'Desenvolvimento Sustentável',
    'Sistemas Distribuídos',
    'Trabalho De Integração 2',
    'Estágio 2',
    'Trabalho De Conclusão De Curso 1',
    'Trabalho De Conclusão De Curso 2',
    ]


minhas_cursadas = [
    'Cálculo Numérico',
    'Física Experimental 1',
    'Física Teórica A',
    'Física Teórica B',
    'Física Teórica C',
    'Expressão Gráfica',
    'Química',
    'Fundamentos De Programação 1',
    'Ciência Dos Materiais Aplicada À Eng Civil',
    'Computação A',
    'Comunicação Oral E Escrita',
    'Cálculo Diferencial E Integral 1',
    'Geometria Analítica E Álgebra Linear',
    'Projeto Arquitetônico',
    'Materiais De Construção',
    'Topografia',
    'Metodologia Da Pesquisa',
    'Física 1',
    'Introdução À Administração',
    'Cálculo Diferencial E Integral 2',
    'Argamassas E Concretos',
    'Mecânica Geral 1',
    'Física 2',
    'Economia',
    'Equações Diferenciais Ordinárias',
    'Probabilidade E Estatística',
    'Cálculo Diferencial E Integral 3',
    'Gestão Ambiental',
    'Resistência Dos Materiais 1',
    'Métodos Numéricos Aplicados À Engenharia Civil',
    'Hidrologia',
    'Mecânica Geral 2',
    'Física 3',
    'Contabilidade E Gestão De Custos',
    'Tecnologia Da Construção De Edifícios 1',
    'Instalações Elétricas Prediais',
    'Mecânica Dos Fluidos E Transferência De Calor',
    'Resistência Dos Materiais 2',
    'Geologia Aplicada À Engenharia',
    'Engenharia De Segurança Do Trabalho',
    'Gestão De Pessoas',
]
